title: Jakob Øvrum
site.title: Jakob Øvrum's D blog
tagline: D programming

destination: ./d/_site
safe: true
permalink: date
markdown: redcarpet
highlighter: 'pygments'
lsi: false
gems:
  - jekyll-paginate
  - jekyll-feed
baseurl: /d

paginate: 5
paginate_path: "page:num"
