title: Jakob Øvrum's D blog
tagline: D programming

destination: ./d/_site
safe: false
permalink: date
markdown: kramdown
highlighter: rouge
lsi: false
gems:
  - jekyll-paginate
  - jekyll-feed

feed:
  path: /d/feed.xml

paginate: 5
paginate_path: "/d/page:num"
